### ISSUE TITLE
Please create a guide using this new updated Darwinbuild.

### ISSUE THREAD

**Issue by csekel** [csekel/darwinbuild#32]

**Comment by wjk** [comment]
[Here is a first draft of a guide to darwinbuild](https://github.com/PureDarwin/darwinbuild/blob/documentation/Documentation/creating_darwinbuild_plists.md), for anyone who’s interested.

**Comment by maldiohead** [comment]
need new build  document

**Comment by wjk** [comment]
@maldiohead Unfortunately, building PureDarwin completely from source, using darwinbuild or otherwise, is decidedly nontrivial. There are numerous projects which each need to be built and installed, each of which requiring substantial patching before they will compile. I have yet to get it to work myself in fact.

@csekel originally provided me with the current PureDarwin image; I suggest you contact him via the email address on his GitHub profile. I am sorry I cannot help you further.

**Comment by csekel** [comment]
@maldiohead You will need to understand what each project needs as dependency you can see from this plist to get an idea(https://github.com/PureDarwin/PureDarwin-System-Plist/blob/master/16D32pd1.plist) like if a project/target is in a project as an example look at ctftools within that plist.
